<?php

namespace Database\Seeders;

use App\Models\Chart;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ChartSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Chart::insert([
            [ // chart id 1
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 2
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 3
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 4
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 5
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 6
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 7
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 8
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 9
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 10
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 11
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 12
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 13
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 14
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 15
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 16
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 17
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 18
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 19
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 20
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 21
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 22
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 23
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 24
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 25
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 26
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 27
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 28
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 29
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 30
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 31
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 32
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 33
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 34
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 35
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 36
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 37
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 38
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 39
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 40
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 41
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 42
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 43
                'bn_name' => '', 
                'en_name' => '',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
        ]);
    }
}
