<?php

namespace Database\Seeders;

use App\Models\Chart;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ChartSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Chart::insert([
            [ // chart id 1
                'bn_name' => 'লিঙ্গভেদে শিক্ষার্থী বিন্যাস', 
                'en_name' => 'Gender wise Distribution of Students ',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => 'Classes are balanced between boys and girls in primary and secondary schools',
                'en_description' => 'Classes are balanced between boys and girls in primary and secondary schools',
            ],
            [ // chart id 2
                'bn_name' => 'লিঙ্গভেদে শিক্ষক বিন্যাস', 
                'en_name' => 'Gender-wise Distribution of Teachers  ',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => 'While the ratio of female teachers is trending up, it still remains male-dominated.',
                'en_description' => 'While the ratio of female teachers is trending up, it still remains male-dominated.',
            ],
            [ // chart id 3
                'bn_name' => 'কোভিড-১৯ চলাকালীন সময়ে অনলাইন ক্লাসে উপস্থিতির হার', 
                'en_name' => 'Attendance Rate in Online Class in COVID-19',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => 'এপ্রিল ২০ থেকে এপ্রিল ২১ পর্যন্ত ৬০%-এর বেশি উপজেলায় ৫০%-এর কম শিক্ষার্থী অনলাইনে উপস্থিত থাকে ।',
                'en_description' => 'In more than 60% of Upazillas have less than 50% of the students attend online classes from April 20 to April 21.',
            ],
            [ // chart id 4
                'bn_name' => 'কোভিড-১৯ চলাকালীন সময়ে শিক্ষার্থীদের অনলাইন ক্লাসে অংশগ্রহণে অনীহার কারণসমূহ', 
                'en_name' => 'Challenges in Online Class (Student) in COVID-19  ',
                'bn_datasource' => 'Upazila Secondary Education Officer Survey (Aspire to Innovate-a2i & Innovations for Poverty Action-IPA), 2020',
                'en_datasource' => 'Upazila Secondary Education Officer Survey (Aspire to Innovate-a2i & Innovations for Poverty Action-IPA), 2020',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 5
                'bn_name' => 'কোভিড-১৯ চলাকালীন সময়ে শিক্ষকদের অনলাইন ক্লাস গ্রহণের বাধাসমূহ', 
                'en_name' => 'Challenges in Online Class (Teachers) in COVID-19  ',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 6
                'bn_name' => 'গ্রামের এবং শহরের বিদ্যালয়ে বিদ্যুৎ সংযোগের প্রবণতা', 
                'en_name' => 'Trends in electricity connection in rural and urban schools  ',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => 'Though in 2019 the access to electricity dropped suddenly, in 2020 the access to electricity is again increasing.',
                'en_description' => 'Though in 2019 the access to electricity dropped suddenly, in 2020 the access to electricity is again increasing.',
            ],
            [ // chart id 7
                'bn_name' => 'গ্রামের এবং শহরের বিদ্যালয়ে ইন্টারনেট ব্যবহারের প্রবণতা', 
                'en_name' => 'Trends in internet access in rural and urban schools  ',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => 'Though internet access has been cited as one of the challenges, most schools do have internet access. However, these could be due to low quality which is not immediately known.',
                'en_description' => 'Though internet access has been cited as one of the challenges, most schools do have internet access. However, these could be due to low quality which is not immediately known.',
            ],
            [ // chart id 8
                'bn_name' => 'গ্রামের এবং শহরের বিদ্যালয়ে ওয়েবসাইট থাকার প্রবণতা', 
                'en_name' => 'Trends in having websites in rural and urban schools ',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => 'This is an encouraging trend. However, the data could not be verified, and most of the websites may not be functional.',
                'en_description' => 'This is an encouraging trend. However, the data could not be verified, and most of the websites may not be functional.',
            ],
            [ // chart id 9
                'bn_name' => 'কোভিড-১৯ চলাকালীন সময়ে উপজেলা শিক্ষা অফিসারের সম্মুখে আসা বাধাসমূহ', 
                'en_name' => 'Challenges faced by Upazila Education Officers during COVID-19  ',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => 'Resource constraints, both human and financial resources, remain the two biggest challenges.',
                'en_description' => 'Resource constraints, both human and financial resources, remain the two biggest challenges.',
            ],
            [ // chart id 10
                'bn_name' => 'কোভিড-১৯ চলাকালীন সময়ে উপজেলা শিক্ষা অফিসারের গ্রহণ করা পদক্ষেপসমূহ', 
                'en_name' => 'Steps Taken by Upazila Education Officers in COVID-19',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => 'These self-reported steps described by the USEO do not fit with the reality of online classes. There should be scope for third-party verification.',
                'en_description' => 'These self-reported steps described by the USEO do not fit with the reality of online classes. There should be scope for third-party verification.',
            ],
            [ // chart id 11
                'bn_name' => 'কোভিড-১৯ এর মতো সংকট মোকাবিলায় USEO-এর ভবিষ্যত পরিকল্পনা।', 
                'en_name' => 'Plan of USEO for crisis like COVID-19 in future',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => 'Most of the USEOs want to ensure sufficient resources for online class in addition to spreading awareness for crises like COVID-19. ',
                'en_description' => 'Most of the USEOs want to ensure sufficient resources for online class in addition to spreading awareness for crises like COVID-19. ',
            ],
            [ // chart id 12
                'bn_name' => 'বার্ষিক প্রকৃত মোট দেশজ উৎপাদন (জিডিপি)', 
                'en_name' => 'Yearly Real Gross Domestic Product (GDP)  ',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 13
                'bn_name' => 'দক্ষতার স্তর ভেদে বৈদেশিক কর্মসংস্থান হওয়া কর্মীর সংখ্যা', 
                'en_name' => 'Amount of Overseas Employment across Skill Level',
                'bn_datasource' => 'ব্যুরো অফ ম্যানপাওয়ার, এমপ্লয়মেন্ট অ্যান্ড ট্রেইনিং (বিএমইটি) ',
                'en_datasource' => 'Bureau of Manpower, Employment and Training (BMET)',
                'bn_description' => 'Overseas employment, which remains one of the main sources of foreign remittance of the country has relied mostly on the export of low-skilled labor. However, in recent years, the employment of both skilled and semi-skilled labor has increased where skilled labor has surpassed the low-skilled category. This is a welcoming development, which will increase both the inward remittance flow as well as further export of higher-skilled labor overseas.',
                'en_description' => 'Overseas employment, which remains one of the main sources of foreign remittance of the country has relied mostly on the export of low-skilled labor. However, in recent years, the employment of both skilled and semi-skilled labor has increased where skilled labor has surpassed the low-skilled category. This is a welcoming development, which will increase both the inward remittance flow as well as further export of higher-skilled labor overseas.',
            ],
            [ // chart id 14
                'bn_name' => 'মুদ্রাস্ফীতির হার', 
                'en_name' => 'Inflation Rate',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 15
                'bn_name' => 'মোট দেশজ উৎপাদনের (জিডিপি) খাতসমূহ', 
                'en_name' => 'GDP Composition',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 16
                'bn_name' => 'জেলা ভেদে বার্ষিক বৈদেশিক আয়', 
                'en_name' => 'District-wise Remittance over the Years',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 17
                'bn_name' => 'জেলা ভেদে বার্ষিক বৈদেশিক আয়', 
                'en_name' => 'District-wise Remittance over the Years',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => 'Most overseas remittance flows to Dhaka and Chattogram regions. Sylhet, which was once the centre of overseas remittance flows now stands as the distant third in the remittance league table. The share of other regions, especially that of north and south remains insignificant.This flow reflects several facts including the uneven growth of different regions within the country.  ',
                'en_description' => 'Most overseas remittance flows to Dhaka and Chattogram regions. Sylhet, which was once the centre of overseas remittance flows now stands as the distant third in the remittance league table. The share of other regions, especially that of north and south remains insignificant.This flow reflects several facts including the uneven growth of different regions within the country.  ',
            ],
            [ // chart id 18
                'bn_name' => 'মোট কর্মসংস্থান এবং বৈদেশিক আয়', 
                'en_name' => 'Total Employment & Remittance ',
                'bn_datasource' => 'ব্যুরো অফ ম্যানপাওয়ার, এমপ্লয়মেন্ট অ্যান্ড ট্রেইনিং (বিএমইটি)',
                'en_datasource' => 'Bureau of Manpower, Employment and Training (BMET)',
                'bn_description' => 'Both overseas employment and incoming remittance flows have been consistently increasing over the years. However, they respond to large-scale economic and health shocks such as the COVID-19 pandemic when overseas employment went down dramatically. Following the COVID-19 shock, the remittance inflow and employment behaved in opposite directions probably due to the fact that workers brought all their overseas savings back with them when they lost their employments and returned home. Policies need to focus on how to accommodate the returnees to local job markets, how to use their experience to send others overseas in the future and to reinvest the remittance in the economy.',
                'en_description' => 'Both overseas employment and incoming remittance flows have been consistently increasing over the years. However, they respond to large-scale economic and health shocks such as the COVID-19 pandemic when overseas employment went down dramatically. Following the COVID-19 shock, the remittance inflow and employment behaved in opposite directions probably due to the fact that workers brought all their overseas savings back with them when they lost their employments and returned home. Policies need to focus on how to accommodate the returnees to local job markets, how to use their experience to send others overseas in the future and to reinvest the remittance in the economy.',
            ],
            [ // chart id 19
                'bn_name' => 'জেলা-ভেদে বৈদেশিক কর্মসংস্থান হওয়া কর্মীদের সংখ্যা (শতকরা হারে)', 
                'en_name' => 'District-wise % Change in Overseas Employment ',
                'bn_datasource' => 'ব্যুরো অফ ম্যানপাওয়ার, এমপ্লয়মেন্ট অ্যান্ড ট্রেইনিং (বিএমইটি)',
                'en_datasource' => 'Bureau of Manpower, Employment and Training (BMET)',
                'bn_description' => 'In 2020 owing to the COVID-19 shock, new overseas employment declined across the board. The average year-to-year decline was about 70% with some districts experiencing a much higher fall in overseas employment. However, effects are heterogeneous as few districts far better than others.',
                'en_description' => 'In 2020 owing to the COVID-19 shock, new overseas employment declined across the board. The average year-to-year decline was about 70% with some districts experiencing a much higher fall in overseas employment. However, effects are heterogeneous as few districts far better than others.',
            ],
            [ // chart id 20
                'bn_name' => 'উৎস অনুসারে বৈদেশিক আয়ের পরিমাণ', 
                'en_name' => 'Source-wise Amount of Remittance',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 21
                'bn_name' => 'দেশ ভেদে বৈদেশিক আয়ের পরিমাণ', 
                'en_name' => 'Country-wise Remittance ',
                'bn_datasource' => 'বাংলাদেশ ব্যাংক',
                'en_datasource' => 'Bangladesh Bank',
                'bn_description' => 'In the last decade, the main source countries for overseas remittance have been the UAE and the USA, followed by the UK, Kuwait, Malaysia, and Qatar. The countries that are becoming increasingly important as sources are Italy, Bahrain, and Singapore. Overall, the resources of remittances are quite diverse reflecting the diversity of the overseas employment types.',
                'en_description' => 'In the last decade, the main source countries for overseas remittance have been the UAE and the USA, followed by the UK, Kuwait, Malaysia, and Qatar. The countries that are becoming increasingly important as sources are Italy, Bahrain, and Singapore. Overall, the resources of remittances are quite diverse reflecting the diversity of the overseas employment types.',
            ],
            [ // chart id 22
                'bn_name' => 'আমদানি-রপ্তানির বার্ষিক প্রবণতা', 
                'en_name' => 'Trends in Import-Export Over the Year  ',
                'bn_datasource' => 'বাংলাদেশ ব্যাংক',
                'en_datasource' => 'Bangladesh Bank',
                'bn_description' => 'Import and export follow a fairly cyclical up-then-down pattern. Imports have ever-so-slightly fallen over the last three years, and exports have a slightly positive trend. There is a sizeable dip in both in early 2020, as the world adjusted to the new normal necessitated by the COVID-19 pandemic.',
                'en_description' => 'Import and export follow a fairly cyclical up-then-down pattern. Imports have ever-so-slightly fallen over the last three years, and exports have a slightly positive trend. There is a sizeable dip in both in early 2020, as the world adjusted to the new normal necessitated by the COVID-19 pandemic.',
            ],
            [ // chart id 23
                'bn_name' => 'শীর্ষ আমদানীর দেশসমূহ', 
                'en_name' => 'Top Import Countries',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 24
                'bn_name' => 'দেশ ভেদে আমদানী', 
                'en_name' => 'Country wise Import',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 25
                'bn_name' => 'শীর্ষ রপ্তানীর দেশসমূহ', 
                'en_name' => 'Top Export Countries',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 26
                'bn_name' => 'দেশ ভেদে রপ্তানী', 
                'en_name' => 'Country wise Import',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 27
                'bn_name' => 'দেশ ভেদে রপ্তানীর এরিয়া চার্ট', 
                'en_name' => 'Area chart for country wise exports ',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 28
                'bn_name' => 'ব্যাংকিং লেনদেনের পরিমাণ', 
                'en_name' => 'Amount of Banking Transactions',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => 'Between December 2018 and January 2021, transactions by mobile and internet have almost doubled while Agent transactions increased almost six times. Mobile transactions continue to be the dominant transaction type, with agent transactions gaining some relative share over time.',
                'en_description' => 'Between December 2018 and January 2021, transactions by mobile and internet have almost doubled while Agent transactions increased almost six times. Mobile transactions continue to be the dominant transaction type, with agent transactions gaining some relative share over time.',
            ],
            [ // chart id 29
                'bn_name' => 'ব্যাংকিং লেনদেনের সংখ্যা', 
                'en_name' => 'Number of Banking Transactions',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => 'The number of mobile transactions—like those over bKash—dominate, most likely due to its high accessibility. Between December 2018 to 2021, the quantity of all transaction types increased overall with small intermittent dips.',
                'en_description' => 'The number of mobile transactions—like those over bKash—dominate, most likely due to its high accessibility. Between December 2018 to 2021, the quantity of all transaction types increased overall with small intermittent dips.',
            ],
            [ // chart id 30
                'bn_name' => 'এজেন্ট লেনদেনের পরিমাণঃ শহর- গ্রাম ভেদে', 
                'en_name' => 'Agent Transactions Amount: Urban-Rural Composition',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => 'Between December 2018 and January 2021, transactions by agents in urban areas increased four times and in rural areas, six times. Rural transactions by agents remained the dominant transaction type throughout and also increased more relative to urban transactions by agents. The increase is likely due to the flow of internal remittance from urban areas to rural areas. ',
                'en_description' => 'Between December 2018 and January 2021, transactions by agents in urban areas increased four times and in rural areas, six times. Rural transactions by agents remained the dominant transaction type throughout and also increased more relative to urban transactions by agents. The increase is likely due to the flow of internal remittance from urban areas to rural areas. ',
            ],
            [ // chart id 31
                'bn_name' => 'কোভিড-১৯ চলাকালীন সময়ে বাল্যবিবাহের চিত্র', 
                'en_name' => 'Change in Early marriage due to COVID-19',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 32
                'bn_name' => 'কোভিড-১৯ চলাকালীন সময়ে লিঙ্গভেদে সহিংসতার চিত্র', 
                'en_name' => 'Change in Gender based Violence due to COVID-19  ',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 33
                'bn_name' => 'কোভিড-১৯ চলাকালীন সময়ে শিশুশ্রমের চিত্র', 
                'en_name' => 'Change in Child labor due to COVID-19  ',
                'bn_datasource' => 'Upazila Secondary Education Officer Survey (Aspire to Innovate-a2i & Innovations for Poverty Action-IPA), 2020',
                'en_datasource' => 'Upazila Secondary Education Officer Survey (Aspire to Innovate-a2i & Innovations for Poverty Action-IPA), 2020',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 34
                'bn_name' => 'কোভিড-১৯ চলাকালীন সময়ে বিভাগ ভেদে বাল্যবিবাহের চিত্র', 
                'en_name' => 'Division wise Change in Early marriage due to COVID-19  ',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 35
                'bn_name' => 'কোভিড-১৯ চলাকালীন সময়ে বিভাগ ভেদে লিঙ্গভিত্তিক সহিংসতার চিত্র', 
                'en_name' => 'Division wise Change in Gender based Violence due to Covid-19 ',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 36
                'bn_name' => 'কোভিড-১৯ চলাকালীন সময়ে বিভাগ ভেদে শিশুশ্রমের চিত্র', 
                'en_name' => 'Division wise Change in Child Labor due to COVID-19 ',
                'bn_datasource' => 'Upazila Secondary Education Officer Survey (Aspire to Innovate-a2i & Innovations for Poverty Action-IPA), 2020',
                'en_datasource' => 'Upazila Secondary Education Officer Survey (Aspire to Innovate-a2i & Innovations for Poverty Action-IPA), 2020',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 37
                'bn_name' => 'জেলাভিত্তিক খাদ্য ঘাটতি', 
                'en_name' => 'District Wise Food Insecurity',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => 'Rajshahi, Rangpur and Sylhet (North-eastern) regions are more vulnerable to food insecurity whereas the Khulna and Chittagong southern regions have low vulnerability in Bangladesh. Therefore, resources should be allocated targeting the regions with more food insecurity.',
                'en_description' => 'Rajshahi, Rangpur and Sylhet (North-eastern) regions are more vulnerable to food insecurity whereas the Khulna and Chittagong southern regions have low vulnerability in Bangladesh. Therefore, resources should be allocated targeting the regions with more food insecurity.',
            ],
            [ // chart id 38
                'bn_name' => 'প্রোগ্রাম এবং প্রোগ্রামের ধরণ অনুসারে বাজেটের বন্টন', 
                'en_name' => 'Budget across Programs and Program Types',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 39
                'bn_name' => 'প্রোগ্রাম এবং প্রোগ্রামের ধরণ অনুসারে সুবিধাভোগীর সংখ্যা', 
                'en_name' => 'Coverage across Programs and Program Types',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 40
                'bn_name' => 'বাস্তবায়নকারী মন্ত্রণালয়', 
                'en_name' => 'Implementing Minisry',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 41
                'bn_name' => 'সামাজিক সুরক্ষা খাতে বাজেট এবং সুবিধাভোগীর সংখ্যা', 
                'en_name' => 'SSN Budget & Coverage',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 42
                'bn_name' => 'সামাজিক সুরক্ষা খাতে বার্ষিক বরাদ্দ বাজেটঃ শীর্ষ ৫ খাত', 
                'en_name' => 'SSN top 5 program Budget across years',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 43
                'bn_name' => 'সামাজিক সুরক্ষা খাতে বার্ষিক সুবিধাভোগীর সংখ্যাঃ শীর্ষ ৫ খাত', 
                'en_name' => 'SSN top 5 program Coverage across years',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 44
                'bn_name' => 'Poverty rate BBS', 
                'en_name' => 'Poverty rate BBS',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 45
                'bn_name' => 'Poverty Index OPHI', 
                'en_name' => 'Poverty Index OPHI',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 46
                'bn_name' => 'Poverty Index WB', 
                'en_name' => 'Poverty Index WB',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
            [ // chart id 47
                'bn_name' => 'Poverty & Squared Poverty Gap BBS', 
                'en_name' => 'Poverty & Squared Poverty Gap BBS',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],

            [ // chart id 48
                'bn_name' => 'Poverty Rate Regional', 
                'en_name' => 'Poverty Rate Regional',
                'bn_datasource' => '',
                'en_datasource' => '',
                'bn_description' => '',
                'en_description' => '',
            ],
        ]);
    }
}
